name: ci

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

jobs:
  check:
    name: just-check
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Run standard checks
        run: just check
